import os
from groq import Groq

# Initialize client with API key from environment variable
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

SYSTEM_PROMPT = """
You are an AI document analyst.

Rules:
1. Answer ONLY using the provided sources.
2. If the answer is not found, say: "I don't know based on the documents."
3. Cite sources using [Source X].
4. Be concise, factual, and accurate.
"""

def generate_answer(context: str, question: str) -> str:
    """
    Generate an answer to a question based on provided context using Groq LLM.
    
    Args:
        context (str): Text retrieved from documents relevant to the question.
        question (str): The user’s question.
    
    Returns:
        str: Answer generated by the AI.
    """
    try:
        response = client.chat.completions.create(
            model="groq/compound",  # <- Updated model, currently supported
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": f"Context:\n{context}\n\nQuestion:\n{question}"
                }
            ],
            temperature=0.2,
            max_tokens=500
        )

        return response.choices[0].message.content

    except Exception as e:
        return f"Error generating answer: {str(e)}"
